#**************************************************************************
#*                                                                        *
#*                                 OCaml                                  *
#*                                                                        *
#*            Sébastien Hinderer, projet Gallium, INRIA Paris             *
#*                                                                        *
#*   Copyright 1999 Institut National de Recherche en Informatique et     *
#*     en Automatique.                                                    *
#*                                                                        *
#*   All rights reserved.  This file is distributed under the terms of    *
#*   the GNU Lesser General Public License version 2.1, with the          *
#*   special exception on linking described in the file LICENSE.          *
#*                                                                        *
#**************************************************************************

# Makefile to build ocamltest for Non-Cygwin Windows ports

run := run_windows

include Makefile.shared

%.$(O): %.c
	$(CC) $(CFLAGS) $(BYTECCCOMPOPTS) -c $<